(use compat.sicp)

(define (make-monitored proc)
  (let ((counter 0))
    (define (execute-proc arg)
      (set! counter (+ counter 1))
      (proc arg))
    (define (how-many-calls?)
      counter)
    (define (reset-count)
      (set! counter 0))
    (define (mf m)
      (cond ((eq? m 'how-many-calls?) (how-many-calls?))
            ((eq? m 'reset-count) (reset-count))
            (else (execute-proc m))))
  mf))

(define s (make-monitored sqrt))
#?=(s 100)
#?=(s 25)
#?=(s 'how-many-calls?)
#?=(s 'reset-count)
#?=(s 36)
#?=(s 'how-many-calls?)
